[concept]

# Only process PICA+ records as concepts, which match against the given filter
# expression.
filter = "002@.0 =~ '^T[bfgpsu][1z]$' && 008A.a == 's' && !008@.a? && 007K.a == 'gnd'"

# Whether to skip invalid PICA+ records or not.
skip_invalid = true

# Ignore synonyms less than `min_synonym_length`.
min_synonym_length = 4

# Ignore synonyms which match against `synonym_filter`.
# synonym_filter = "\\(.*Motiv\\)$"

# Ignore synonyms (only persons), when forename (subfield $d)
# contains a single character followed by a ".".
# person_no_initials = true

# Ignore synonyms (only persons), when the pref-labels contains
# subfields $d and $a and an alternative label contains only one
# word.
person_no_modern_names = true

# Use `base_uri` + IDN instead of GND ID
base_uri = "http://d-nb.info/gnd/"

# Transliterate synonyms
translit = "nfd"

# [[collection]]
# name = "GND Subject Category"
# path = "042A.a"
# base_uri = "http://d-nb.info/standards/vocab/gnd/gnd-sc#"
# filter = "^(\\d+|\\d+\\.\\d+)[a-z]*$"
# minimum = 2
# maximum = 1000

# [[collection]]
# name = "Geographic Area Code"
# path = "042B.a"
# base_uri = "http://d-nb.info/standards/vocab/gnd/geographic-area-code#"

# [[collection]]
# name = "GND Entity Codes"
# path = "004B.a"
# base_uri = "http://d-nb.info/aen/entity-code#"
# filter = "^[a-z]+$"

# [[collection]]
# name = "DDC Subject Category"
# path = "037G.c"
# base_uri = "http://dewey.info/class/"
# filter = "^[TABC0-9\\.\\-]+$"

[skosify]

# Whether to beautify (indent, prefixes) the output or not.
pretty = true

# Use this language tag for all labels.
language_tag = "de"
