[concept]

# Only process PICA+ records as concepts, which match against the given filter
# expression.
filter = "002@.0 =~ '^T[bfgpsu][1z]$' && 008A.a == 's' && !008@.a? && 007K.a == 'gnd'"

# Whether to skip invalid PICA+ records or not.
skip_invalid = true

# Use `base_uri` + IDN instead of GND ID
base_uri = "http://d-nb.info/gnd/"
gnd_id = false

# Transliterate synonyms
translit = "nfc"

[skosify]

# Whether to beautify (indent, prefixes) the output or not.
pretty = true
