[concept]

# Only process PICA+ records as concepts, which match against the given filter
# expression.
filter = "002@.0 =~ '^T[bfgpsu][1z]$' && 008A.a == 's' && !008@.a? && 007K.a == 'gnd'"

# Whether to skip invalid PICA+ records or not.
skip_invalid = true

# Base-URI for concepts.
base_uri = "http://d-nb.info/gnd/"

# Whether to use GND ID or `base_uri` + IDN as concept uri.
gnd_id = false


